/**
 * Icon — the only way icons should be rendered in this app.
 *
 * Draws from the self-hosted sprite at /icons/sprite.svg, which is generated by
 * `node scripts/build-icons.mjs` from scripts/icons/icon-set.mjs. The sprite is a
 * single immutable, long-cached file, so icon artwork is fetched once and never
 * enters the JavaScript bundle.
 *
 * Accessibility: icons are decorative by default and hidden from assistive
 * technology. Pass a `title` only when the icon is the sole carrier of meaning —
 * an icon-only button, for example — and it becomes an img-role element with an
 * accessible name. When the icon sits beside a visible text label, leave `title`
 * off so screen readers do not announce it twice.
 *
 *   <Icon name="heart" size={18} />                        decorative
 *   <button><Icon name="send" title="Send message" /></button>   named
 */

const SPRITE = '/icons/sprite.svg';

export default function Icon({
    name,
    size = 20,
    title = '',
    className = '',
    strokeWidth,
    style,
    ...rest
}) {
    if (!name) return null;

    const labelled = Boolean(title);

    return (
        <svg
            width={size}
            height={size}
            className={className}
            style={strokeWidth ? { strokeWidth, ...style } : style}
            role={labelled ? 'img' : undefined}
            aria-label={labelled ? title : undefined}
            aria-hidden={labelled ? undefined : 'true'}
            focusable="false"
            {...rest}
        >
            <use href={`${SPRITE}#${name}`} />
        </svg>
    );
}
