/**
 * Builds public/icons/sprite.svg from scripts/icons/icon-set.mjs.
 *
 * The sprite is one cacheable file referenced via <use href="/icons/sprite.svg#name">,
 * so icon artwork leaves the JavaScript bundle entirely and is fetched once.
 *
 * Also reports coverage: it scans src/ for names still imported from lucide-react
 * and fails if any of them has no counterpart in the set, so the migration cannot
 * be left half-done silently.
 *
 *   node scripts/build-icons.mjs
 */

import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, extname } from 'node:path';
import { ICONS, STROKE_DEFAULTS } from './icons/icon-set.mjs';

const SRC = join(process.cwd(), 'src');
const OUT_DIR = join(process.cwd(), 'public', 'icons');
const OUT_FILE = join(OUT_DIR, 'sprite.svg');

/** PascalCase lucide name -> kebab-case sprite id. */
export function toKebab(name) {
    return String(name)
        .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
        .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
        // Trailing digits are a separate segment: BarChart3 -> bar-chart-3,
        // not bar-chart3. Lucide uses them as size/variant suffixes.
        .replace(/([A-Za-z])(\d)/g, '$1-$2')
        .toLowerCase();
}

async function walk(dir) {
    const out = [];
    for (const entry of await readdir(dir, { withFileTypes: true })) {
        const full = join(dir, entry.name);
        if (entry.isDirectory()) out.push(...await walk(full));
        else if (['.js', '.jsx'].includes(extname(entry.name))) out.push(full);
    }
    return out;
}

async function lucideNamesInSource() {
    const names = new Set();
    for (const file of await walk(SRC)) {
        const text = await readFile(file, 'utf8');
        for (const match of text.matchAll(/import\s*\{([^}]+)\}\s*from\s*'lucide-react'/g)) {
            for (const raw of match[1].split(',')) {
                const name = raw.trim().split(/\s+as\s+/)[0].trim();
                if (name) names.add(name);
            }
        }
    }
    return [...names].sort();
}

/** kebab sprite id -> PascalCase export name. Inverse of toKebab. */
export function toPascal(kebab) {
    return String(kebab).split('-').map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join('');
}

const attrs = Object.entries(STROKE_DEFAULTS).map(([k, v]) => `${k}="${v}"`).join(' ');

const symbols = Object.entries(ICONS)
    .map(([name, body]) => `<symbol id="${name}" viewBox="0 0 24 24" ${attrs}>${body}</symbol>`)
    .join('\n');

const sprite = `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n${symbols}\n</svg>\n`;

await mkdir(OUT_DIR, { recursive: true });
await writeFile(OUT_FILE, sprite, 'utf8');

/*
 * Barrel of named wrappers.
 *
 * Icons are used two ways in this codebase: as JSX tags (<Heart size={16} />) and
 * as component values passed to other components (icon={Heart}, { icon: Users }).
 * There are ~120 of the latter. Exporting one thin wrapper per name means both
 * forms keep working, so migrating off lucide-react is a change of import
 * specifier and nothing else — no call-site churn, and nothing to get wrong.
 */
const barrel = [
    '// GENERATED by scripts/build-icons.mjs - do not edit by hand.',
    '//',
    '// Named icon components backed by the self-hosted sprite. Import these instead',
    '// of lucide-react. Each is a thin wrapper around <Icon>, so both JSX usage and',
    '// value usage (icon={Heart}) behave exactly as before.',
    '//',
    '// Add or edit artwork in scripts/icons/icon-set.mjs, then re-run the builder.',
    '',
    "import Icon from '@/components/Icon';",
    '',
    ...Object.keys(ICONS).map((name) =>
        `export const ${toPascal(name)} = (props) => <Icon name="${name}" {...props} />;`),
    '',
].join('\n');

await writeFile(join(process.cwd(), 'src', 'components', 'icons.js'), barrel, 'utf8');

const remaining = await lucideNamesInSource();
const missing = remaining.filter((name) => !ICONS[toKebab(name)]);

console.log(`Wrote ${Object.keys(ICONS).length} symbols to public/icons/sprite.svg`);
console.log(`Sprite size: ${(Buffer.byteLength(sprite) / 1024).toFixed(1)} KB`);

if (remaining.length) {
    console.log(`\nStill importing from lucide-react: ${remaining.length} name(s)`);
}
if (missing.length) {
    console.error(`\nNo sprite symbol for ${missing.length} name(s):`);
    for (const name of missing) console.error(`  ${name}  ->  ${toKebab(name)}`);
    process.exitCode = 1;
} else if (remaining.length) {
    console.log('Every one has a sprite symbol; run the codemod to switch call sites.');
} else {
    console.log('No lucide-react imports remain.');
}
