/**
 * Migrates icon imports off lucide-react onto the self-hosted sprite.
 *
 *   import { Heart, Send } from 'lucide-react';
 *   ->
 *   import { Heart, Send } from '@/components/icons';
 *
 * That is the entire change. src/components/icons.js (generated by
 * scripts/build-icons.mjs) exports a matching named wrapper for every icon, so
 * JSX usage (<Heart />) and value usage (icon={Heart}, { icon: Users }) both keep
 * working untouched. Rewriting ~230 JSX tags — and missing the ~120 value usages —
 * would have been far riskier for no benefit.
 *
 * Names with no sprite symbol are reported and left alone rather than silently
 * producing an undefined import.
 *
 *   node scripts/migrate-icons.mjs --dry     # report only
 *   node scripts/migrate-icons.mjs           # apply
 */

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, extname } from 'node:path';
import { ICONS } from './icons/icon-set.mjs';
import { toKebab } from './build-icons.mjs';

const SRC = join(process.cwd(), 'src');
const DRY = process.argv.includes('--dry');

async function walk(dir) {
    const out = [];
    for (const entry of await readdir(dir, { withFileTypes: true })) {
        const full = join(dir, entry.name);
        if (entry.isDirectory()) out.push(...await walk(full));
        else if (['.js', '.jsx'].includes(extname(entry.name))) out.push(full);
    }
    return out;
}

let changed = 0;
let skipped = 0;

for (const file of await walk(SRC)) {
    const text = await readFile(file, 'utf8');
    const match = text.match(/import\s*\{([^}]+)\}\s*from\s*'lucide-react'/);
    if (!match) continue;

    // For `Image as ImageIcon`, the name that must exist in the barrel is the
    // exported one (`Image`), not the local alias. Take the part before `as`.
    const names = match[1]
        .split(',')
        .map((raw) => raw.trim().split(/\s+as\s+/)[0].trim())
        .filter(Boolean);

    const missing = names.filter((name) => !ICONS[toKebab(name)]);
    if (missing.length) {
        console.error(`SKIP ${file.replace(process.cwd(), '.')} - no symbol for: ${missing.join(', ')}`);
        skipped += 1;
        continue;
    }

    const updated = text.replace(/(import\s*\{[^}]+\}\s*from\s*)'lucide-react'/, "$1'@/components/icons'");
    if (!DRY) await writeFile(file, updated, 'utf8');
    changed += 1;
    console.log(`${DRY ? '[dry] ' : ''}${file.replace(process.cwd(), '.')}  (${names.length} icons)`);
}

console.log(`\n${DRY ? 'Would update' : 'Updated'} ${changed} files.${skipped ? `  Skipped ${skipped}.` : ''}`);
